# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCaptioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='image-captioning')),
                ('caption', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'image_captioning',
            },
        ),
    ]
