# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captioning', '0002_auto_20170219_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecaptioning',
            old_name='image',
            new_name='file',
        ),
    ]
