# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=b'')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'vqa',
            },
        ),
    ]
